version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    ports:
      - "50051:50051"
    depends_on:
      - postgres

  task-service:
    build: ./task-service
    ports:
      - "50052:50052"
    depends_on:
      - postgres

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - task-service
